language: java
services:
  - mysql
sudo: required
jdk: oraclejdk8
before_script:
  - git describe > version.txt
  - mysql -e 'create database sun_aggr;'
  - cp database.yml.travis database.yml
script: mvn clean test site


